name: Main

on:
  push:
    branches: ["main", "dev"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - name: Production
        if: github.ref_name == 'main'
        run: echo "ENVIRONMENT=production" >> $GITHUB_ENV
      - name: Development
        if: github.ref_name == 'dev'
        run: echo "ENVIRONMENT=development" >> $GITHUB_ENV
      
      - name: Clone
        run: |
          cd ..
          rm -rf MAAL
          git clone git@github.com-MAAL:LokenSoftware/MAAL.git
          cd MAAL
          git checkout origin/${GITHUB_REF#refs/heads/}
      
      - name: Install
        run: yarn install --frozen-lockfile
      
      - name: Build
        run: yarn run build-${{ env.ENVIRONMENT }}
      
      #- name: Test
      #  run: yarn test
  
  Deploy:
    runs-on: self-hosted
    needs:
      - Build
    
    if: github.ref_name == 'main'
    
    steps:
      - name: Replace process
        run: |
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop node-MAAL.service
          rm -rf /var/www/MAAL
          mv .output /var/www/MAAL
          sudo systemctl start node-MAAL.service
