name: Main

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - name: Clone
        run: |
          rm -rf MAAL
          git clone git@github.com-MAAL:LokenSoftware/MAAL.git .
          git checkout origin/main
      
      - name: Install
        run: yarn install --frozen-lockfile
      
      - name: Build
        run: yarn run build-release
      
      #- name: Test
      #  run: yarn test
  
  Deploy:
    runs-on: self-hosted
    needs:
      - Build
    
    # Only deploy on main
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Transfer files
        run: scp -r output ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/MAAL.API
      
      - name: Replace process
        run: |
          ssh -t ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop node-MAAL.service
          rm -rf /var/www/MAAL
          mv ~/MAAL.API /var/www/MAAL
          sudo systemctl start node-MAAL.service
          EOF
